### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by SamTebbs33** [ash-lang/maple#1]
# TODO
- [ ] Commands
  - [ ] login (sets github user info)
  - [ ] publish
  - [ ] sync (refreshes dependencies)
  - [ ] run (runs project jar file)
- [ ] Changes
  - [ ] initialise a git repo when creating a new project
  - [ ] add an option for generating a .travis.yml
  - [ ] add dependencies to class-path when building and running
